import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Header from "./components/Header";
import MailList from "./components/MailList";

///"https://create.t3.gg/en/usage/first-steps"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MailList></MailList>
    </>
  );
};

export default Home;
